trigger:
- main

pool:
  vmImage: macos-12

steps:
- task: MSBuild@1
  inputs:
    solution: '**/*Test.UI.csproj'
    configuration: 'Release'
    msbuildArguments: '/p:OutputPath="$(OUT)'
    restoreNugetPackages: true

- script: ls $(OUT)
  
- task: UseNode@1
  inputs:
    version: '10.15.1'   

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'priv.p12'
    certPwd: '71667166'
    keychain: 'temp'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'MSChatProd.mobileprovision'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'


- script: |
    cd Chat.Mobile
    dotnet workload restore 
    dotnet build -f net6.0-ios -c Release
    cd ..
    cd $(OUT)
    ls
    appcenter test run uitest --app "AliRezaFarahnak/Chat.iOS" --devices ce5227fa --app-path '$(OUT)ms.chat.mobile.ipa' --test-series "master" --locale "en_US" --build-dir '$(OUT)' --uitest-tools-dir '$(OUT)' --token $(appcentertoken)
