name: Chat.Mobile.iOS
on: push

jobs:
  build_with_signing:
    runs-on: macos-12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: P12 Install
        # You may pin to the exact commit or the version.
        # uses: Apple-Actions/import-codesign-certs@253ddeeac23f2bdad1646faac5c8c2832e800071
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-filepath: 'Chat.Mobile/AppleDistribution.p12'
          p12-password: ${{ secrets.P12_PASSWORD }} 
          
      - name: Provisioning Profile Install
        uses: akiojin/install-provisioning-profile-github-action@v1.0
        with:
          path: 'Chat.Mobile/MSChatProd.mobileprovision'

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          
      - name: Build IPA
        run: |
          cd Chat.Mobile
          dotnet workload restore 
          dotnet build -f net6.0-ios -c Release
          cd ..
          cd Chat.Mobile/bin/Release/net6.0-ios/ios-arm64
          ls
