name: Chat.Mobile.iOS

on:
  push:
    paths-ignore:
      - 'Chat.Hub/**'
      - 'Chat.Blazor/**'
      - '**/microsoft-chat-hub.yml'
      - '**/microsoft-chat-blazor.yml'
      - '**/microsoft-chat-mobile-android.yml'
      - 'README.md'
    branches:
      - main
      
jobs:
  Build:
    runs-on: [self-hosted, macOS, x64]
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd /Chat.Mobile/
          ls
          dotnet build -f net6.0-ios -c Release -o /Users/ali/Desktop/iosapp
          cd /Users/ali/Desktop/iosapp
          ls
          
      - run: echo hello
  
  Integration:
    runs-on: windows-latest
    needs: Build
    steps:        
      - run: echo hello
  UI:
    runs-on: windows-latest
    needs: Integration
    steps:
      - run: echo hello
      
  Internal:
    runs-on: windows-latest
    needs: UI
    steps:
      - run: echo hello
        
  AppStore:
    runs-on: windows-latest
    needs: Internal
    steps:
      - run: echo hello
        
